# Generated by Django 4.0.8 on 2022-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
